server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    #    url: jdbc:mysql://mysql-springboot-container:3306/e-commerce-microservice
    url: jdbc:mysql://localhost:3306/e-commerce
    username: root
    password: Dfer2205me
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

# secretPsw
secretPsw: kasdjhfkadhsY776ggTyUU65khaskdjfhYuHAwjlji

# cloud storage
storage.cloudinary.cloudName : djia7tn8l
storage.cloudinary.apiKey : 178746625816242
storage.cloudinary.apiSecret : 178746625816242

CLIENT_BASE_URL: http://localhost:3000

webhook:
  webhook: whsec_e54361f57831a7e93736fda57408ded0a1b066b47c1f13665792d34bed7a2969

stripe:
  secret:
    key: sk_test_51OgOCdLOmLphZ7kVM5nykoqiQWrHmGNr1l9sze8TKIEtNJnxogNdWR4gd3aIVPL4yLAODf0HKJK3SINaRC4t86C800K08LLmEO